Locars/Locars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Locars/listings/urls.py
from unicodedata import name
from django.urls import path
from listings import views


urlpatterns = [
    path('', views.Home, name='Home'),
    path('search/', views.Search, name='Search'),
    path('register/', views.Register, name='Register'),
    path('login/', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
    path('profile/', views.Profile, name='Profile'),
    path('account/', views.Account, name='Account'),
    path('locarist/', views.Locarist, name='Locarist'),
    path('favories/', views.Favories, name='Favories'),
    path('travel/', views.Travel, name='Travel'),
    path('mycars/', views.MyCars, name='MyCars'),
    path('deleteAccount/', views.DeleteAccount, name='DeleteAccount'),
    path('accountDeleted/', views.AccountDeleted, name='AccountDeleted'),
    path('deleteCar/<str:car_id>/', views.DeleteCar, name='DeleteCar'),
    path('locaristPlus/<str:car_id>/', views.LocaristPlus, name='LocaristPlus'),
    path('contact/', views.Contact, name='Contact'),
]

Locars/listings/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, AbstractUser,BaseUserManager
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
#from .managers import UserManager
# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('L\'adresse e-mail est obligatoire.')
        if not username:
            raise ValueError('Le nom d\'utilisateur est obligatoire.')

        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username,email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Le superutilisateur doit avoir is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Le superutilisateur doit avoir is_superuser=True.')

        return self.create_user(username,email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone_no = models.CharField(max_length=15, blank=True)
    profilePicture = models.ImageField(upload_to='profile_picture/',
                                default='profile_picture/default_images/profile_default.jpg')
    #Indique si l'utilisateur est déjà un hôte (default = NON)
    locarist = models.BooleanField(default=False)

    #adresse de l'utilisateur
    country = models.CharField(max_length=42, blank=True)
    city = models.CharField(max_length=58, blank=True)
    street = models.CharField(max_length=50, blank=True)

    date_creation = models.DateTimeField(auto_now_add=True)

    def get_creation_month_year(self):
        return self.date_creation.strftime('%b %Y')

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Car(models.Model):
    
    FUEL_CHOICES = (
        ('A', 'Essence'),
        ('B', 'Diesel'),
        ('C', 'Hybride'),
        ('D', 'Électrique'),
    )

    GEARDBOX = {
        ('A', 'Automatique'),
        ('B', 'Manuelle'),
    }

    Id_car = models.CharField(max_length=8, unique=True)
    licence_plate = models.CharField(max_length=20, unique=True)

    marque = models.CharField(max_length=50, default='')
    model = models.CharField(max_length=50, default='')
    year = models.IntegerField(default=0)
    km = models.IntegerField(default=0, blank=True)


    #adresse du Véhicule
    country = models.CharField(max_length=42, blank=False, default='')
    city = models.CharField(max_length=58, blank=False, default='')
    street = models.CharField(max_length=50, blank=False, default='')

    
    #Choix des paramètre de la voiture
    fuel = models.CharField(max_length=1, choices=FUEL_CHOICES, blank=False, default='')
    

    #Informations complémentaire
    nb_door = models.IntegerField(default=0, blank=True, null=True)
    geardbox = models.CharField(max_length=1, choices=GEARDBOX, blank=True, null=True)
    nb_place = models.IntegerField(default=0, blank=True, null=True)
    Price = models.IntegerField(default=0)

    ProfileCarPicture = models.ImageField(upload_to='cars_picture/',
                            default='profile_picture/default_images/cars.png')
    Picture1 = models.ImageField(upload_to='cars_picture/',
                            blank=True)
    Picture2 = models.ImageField(upload_to='cars_picture/',
                            blank=True)
    Picture3 = models.ImageField(upload_to='cars_picture/',
                            blank=True)

    # Déclaration de la clé étrangère vers le modèle User
    username = models.ForeignKey(User, on_delete=models.CASCADE, related_name='car',default='')

    def __str__(self):
        return self.Id_car

"""class User(AbstractUser):
    HOST = 'HOST'
    CLIENT = 'CLIENT'

    ROLE_CHOICES = (
        (HOST, 'Hôte'),
        (CLIENT, 'Client'),
    )

    profile_photo = models.ImageField(upload_to='default_images/', default='profile_default.jpg')
    role = models.CharField(max_length=30, choices=ROLE_CHOICES)
"""

"""class User(AbstractBaseUser, PermissionsMixin):
    
    email = models.EmailField(('adresse mail'), unique=True)
    username = models.CharField(max_length=20, default="")
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    phone_no = models.CharField(max_length=10, default='0000000000')
    role = models.IntegerField(default=0, validators=[
                               MinValueValidator(0), MaxValueValidator(2)])
    picture = models.ImageField(upload_to='default_images/',
                                default='profile_default.jpg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    #objects = UserManager()

    def __str__(self):
        return self.email

"""
"""
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    
    email = models.EmailField(('adresse mail'), unique=True)
    username = models.CharField(max_length=20, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    phone_no = models.CharField(max_length=10, default='0000000000')
    role = models.IntegerField(default=0, validators=[
                               MinValueValidator(0), MaxValueValidator(2)])
    picture = models.ImageField(upload_to='default_images/',
                                default='profile_default.jpg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    #objects = UserManager()
    def get_by_natural_key(self):
        return self.email

    def __str__(self):
        return self.email


"""

Locars/listings/forms.py
from django import forms
from .models import User, Car

class UserForm(forms.ModelForm):
    class Meta:
        
        model = User
        
        fields = ['username', 'email', 'first_name', 'last_name', 'phone_no', 'password']

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['licence_plate', 'marque', 'model', 'year','km', 'country', 'city', 'street', 'fuel']
        exclude = ['username', 'Id_car']

class CarPlusForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['nb_door', 'nb_place', 'geardbox', 'Price', 'ProfileCarPicture', 'Picture1', 'Picture2', 'Picture3']

class ProfilForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['profilePicture', 'first_name', 'last_name']

class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'country', 'city', 'street', 'phone_no']


class EmailForm(forms.Form):
    to_email = forms.EmailField(label='Destinataire')

class SearchCarsForm(forms.Form):
    marque = forms.CharField(max_length=20, required=False)
    model = forms.CharField(max_length=20, required=False)
    city = forms.CharField(max_length=58, required=False)
    country = forms.CharField(max_length=42, required=False)

Locars/listings/templates/listings/Account/Account.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}
    <div class="ProfilePage">

    
        <h1 id="MyProfile">
            Mon Compte
        </h1>
        <br>
        <br>
        <br>
        <div id="FormProfile">
            <form method="post" action="">
            {% csrf_token %}
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" value="{{ user.email }}">
            <br>
            <br>
            <label for="phone_no">Numéro de Téléphone</label>
            <input type="tel" id="phone_no" name="phone_no" required pattern="[0-9]{10}" value="{{ user.phone_no }}">
            <br>
            <br>
            <div id="Adress">
                <label for="country">Pays :</label>
                <input type="text" id="country" name="country" value="{{ user.country }}">
                <br>
                <br>
                <label for="city">Ville</label>
                <input type="text" id="city" name="city" value="{{ user.city }}">
                <br>
                <br>
                <label for="street">Rue</label>
                <input type="text" id="street" name="street" value="{{ user.street }}">
            </div>

            <br>
            <br>

            <button type="submit" class="btn custom-button">Sauvegarder</button>
        </form>
        </div>
        
        <div id="BtnDellAccount">
            <button type="button" class="btn custom-button">
            <a href="{% url 'DeleteAccount' %}" class="ProfilBarDeconnectButton">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                  </svg>
                Supprimer le Compte
            </a>
        </button>
        </div>
        
    </div>
{% endblock %}

Locars/listings/templates/listings/Account/AccountDeleted.html
{% load static %}
{% extends 'Base.html' %}
{% block content %}

    <h1> Votre compte à été supprimer avec succès.</h1>

    <p>Vous allez être rediriger vers la page d'acceuil</p>

    <!-- Ajoutez le script JavaScript pour la redirection -->
    <script>
        setTimeout(function() {
            // Redirection après 5 secondes
            window.location.href = "{% url 'Home' %}";
        }, 3000);  // 5000 millisecondes = 5 secondes
    </script>

</endblock>

Locars/listings/templates/listings/Account/DeleteAccount.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <div class="DeleteAccountPage">
        
        <h2>Supprimer le compte</h2>
        <p>Êtes-vous sûr de vouloir supprimer votre compte ?</p>

            <form method="post" action="">
                {% csrf_token %}
                <button type="submit" class="BtnDeletedAccount" onmouseover="activerBouton()">Supprimer le compte</button>
                <a href="{% url 'Account' %}">
                    <button type="button" class="BtnDeletedAccountExit">
                        Annuler
                    </button>
                </a>
            </form>
    </div>

{% endblock%}

Locars/listings/templates/listings/Account/DeleteCar.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <div class="DeleteAccountPage">
        
        <h2>Supprimer la Voiture</h2>
        <p>Êtes-vous sûr de vouloir supprimer votre voiture ?</p>

        <form method="post" action="">
            {% csrf_token %}
            <button type="submit" class="BtnDeletedAccount" onmouseover="activerBouton()">Supprimer la voiture</button>
            <a href="{% url 'MyCars' %}">
                <button type="button" class="BtnDeletedAccountExit">
                    Annuler
                </button>
            </a>

        </form>
    </div>

{% endblock %}

Locars/listings/templates/listings/Account/Favories.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <h3> Bonjour {{ user.username }} bienvenue sur votre profile</h3>

{% endblock %}

Locars/listings/templates/listings/Account/Locarist.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}
    <div class="LocaristPage">
        <div id="Locarist">
            {% if user.locarist %}

                <h2> Bonjour Locarist </h2>
                
                <h3>Ajouter une Voiture</h3>

            {% else %}
                
                <h2> Bonjour {{ user.username }} bienvenue sur Votre Futur Page de gestion de vos véhicules</h2>

                <h3>Nous allons enregistrer votre premier véhicules ensemble.</h3>

            
            
            {% endif %}
        </div>
        <div id="FormLocarist">
            <form method="post" action="">
                {% csrf_token %}
                <div id="DisplayFlexDirectionColumns">
                    <label for="marque">Marque</label>
                    <input type="text" id="marque" name="marque" value="{{ car.marque }}" required>
                    <br>
                    <label for="model">Modèle :</label>
                    <input type="text" id="model" name="model">
                </div>

                <br>
                <label for="year">Année :</label>
                <input type="text" id="year" name="year">
                <br>
                <label for="licence_plate">Plaque d'Immatriculation :</label>
                <input type="text" id="licence_plate" name="licence_plate">
                <br>
                
                       <label for="km">Compteur Kilométrique :</label>
                <input type="text" id="km" name="km">
                <br>
                
             

                <label>Type de carburant :</label>
                <div id="DisplayFlexDirectionColumns">
                    <input type="radio" name="fuel" value="A" {% if selected_fuel_type == 'A' %}checked{% endif %}> Essence
                    <input type="radio" name="fuel" value="B" {% if selected_fuel_type == 'B' %}checked{% endif %}> Diesel
                    <input type="radio" name="fuel" value="C" {% if selected_fuel_type == 'C' %}checked{% endif %}> Hybride
                    <input type="radio" name="fuel" value="D" {% if selected_fuel_type == 'D' %}checked{% endif %}> Électrique
                </div>
                <br>

                <div id="DisplayFlexDirectionColumns">
                    <label for="country">Pays :</label>
                    <br>
                    <input type="text" id="country" name="country">
                    <br>
                    <br>
                    <label for="city">Ville</label>
                    <input type="text" id="city" name="city">
                </div>
                    <br>
                    <br>
                    <label for="street">Rue</label>
                    <input type="text" id="street" name="street">
                

                <br>
                <br>


              

                <button type="submit" class="btn custom-button">Sauvegarder</button>
            </form>
        </div>

    </div>
{% endblock %}

Locars/listings/templates/listings/Account/LocaristPlus.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <div class="LocaristPage">
        <div id="Locarist">
            {% if user.locarist %}

                <h2> Bonjour Locarist </h2>
                
                <h3>Ajouter une Voiture</h3>

            {% else %}
                
                <h2> Bonjour {{ user.username }} bienvenue sur Votre Futur Page de gestion de vos véhicules</h2>

                <h3>Nous allons enregistrer votre premier véhicules ensemble.</h3>

            
            
            {% endif %}
        </div>

        <div id="FormLocarist">
            <form method="post" action="">
                {% csrf_token %}

                <label for="nb_door">Nombre de Porte</label>
                <input type="number" id="nb_door" name="nb_door">
            
                <br>

                <label for="Price">Prix</label>
                <input type="number" id="Price" name="Price">

                <br>

                <label>Boîte de Vitesse :</label>
                <div id="DisplayFlexDirectionColumns">
                    <input type="radio" name="geardbox" value="A" {% if selected_geardbox_type == 'A' %}checked{% endif %}> Automatique
                    <input type="radio" name="geardbox" value="B" {% if selected_geardbox_type == 'B' %}checked{% endif %}> Manuelle
                </div>
                <br>

                    <label for="nb_place">Nombre de Place :</label>
                    <br>
                    <input type="number" id="nb_place" name="nb_place">
                    <br>
                    <br>
                    <label for="ProfileCarPicture">Upload :</label>
                    <input type="file" id="ProfileCarPicture" name="ProfileCarPicture">
                    <label for="Picture1">Upload :</label>
                    <input type="file" id="Picture1" name="Picture1">
                    <label for="Picture2">Upload :</label>
                    <input type="file" id="Picture2" name="Picture2">
                    <label for="Picture3">Upload :</label>
                    <input type="file" id="Picture3" name="Picture3">

                <br>
                <br>


            

                <button type="submit" class="btn custom-button">Sauvegarder</button>
            </form>
        

    </div>

{% endblock %}

Locars/listings/templates/listings/Account/MyCars.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <div class="LocaristPage">
        <div id="Locarist">
            <h1>Mes Voitures</h1>
            <h1>
                <a href="{% url 'Locarist' %}"><button class="btn btn-success">Ajouter une Voiture</button></a>
            </h1>

            {% for car in cars %}
                <div class = 'box-cars'>
                    <img src="{{ car.ProfileCarPicture.url }}" class="image-ronde">
                    
                    <br>
                    
                    <strong>{{ car.marque }} {{ car.model }} ({{ car.year }}Km)</strong>
                    {{ car.Price }}€
                    
                    <br>
                    <a href="{% url 'Locarist' %}">
                        <button class="btn btn-success">
                            Modifier
                        </button>
                    </a>
                    <div class="dropdown">
                        <button onclick="toggleDropdown()" class="btn btn-secondary">Détails</button>
                    
                        <div id="myDropdown" class="dropdown-content">
                            ID de voiture: {{ car.Id_car }}<br>
                            Plaque d'immatriculation: {{ car.licence_plate }}<br>
                            Carburant: {{ car.get_fuel_display }}<br>
                            Boîte de vitesse: {{ car.get_geardbox_display }}<br>
                        </div>

                    </div>
                    
                    <a href="{% url 'DeleteCar' car_id=car.Id_car %}">
                        <button class="btn btn-danger">
                            Supprimer
                        </button>
                    </a>
                </div>
                

            {% endfor %}
            
        </div>

    </div>
    <script>
        // Fonction pour afficher ou masquer le menu déroulant
        function toggleDropdown() {
            var dropdown = document.getElementById("myDropdown");
            if (dropdown.style.display === "block") {
                dropdown.style.display = "none";
            } else {
                dropdown.style.display = "block";
            }
        }
    
        // Fermer le menu déroulant si l'utilisateur clique en dehors de celui-ci
        window.onclick = function(event) {
            if (!event.target.matches('.dropdown button')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.style.display === "block") {
                        openDropdown.style.display = "none";
                    }
                }
            }
        }
    </script>

{% endblock %}

Locars/listings/templates/listings/Account/Profile.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}
    <div class="ProfilePage">
        <h1 id="MyProfile">
            Mon Profil
        </h1>

        <br>
        
        <div id="NameProfile">
            {{ user.first_name }}
            {{ user.last_name}}
        </div>
        <div id="MemberProfile">
            Membre depuis : {{ user.date_creation | date:"M Y" }}
        </div>
        

        <!--{{ user.nb_voyage }}-->
        <br>
        <br>
        {% for message in messages %}

        <div id="Message" class="{% if message.tags == 'error' %}ErrorMessage{% elif message.tags == 'success' %}SuccessMessage{% endif %}">
            {{ message }}
        </div>

        {% endfor %}
        <br>
        <br>
        <div id="FormProfile">
            <form method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                <label for="profilePicture">Upload :</label>
                <input type="file" id="profilePicture" name="profilePicture">
                <br>
                <br>
                <label for="first_name">Prénom :</label>
                <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}">
                <br>
                <br>
                <label for="last_name">Nom de Famille :</label>
                <input type="text" id="last_name" name="last_name" value="{{ user.last_name}}">
                <br>
                <br>
                <button type="submit" class="btn BtnSaveProfile">Sauvegarder</button>
            </form>
        </div>

        <br>
        <br>
        <br>
    </div>
{% endblock %}

Locars/listings/templates/listings/Account/Travel.html
{% extends 'listings/BaseProfile.html' %}
{% load static %}
{% block content %}

    <h3> Bonjour {{ user.username }} bienvenue sur votre profile</h3>

{% endblock %}